// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsq3zh2JbXK8q4oOF48zdSHsml3vT5k5Y',
    appId: '1:726617485507:android:a5fffb12f4c1c5fd41f276',
    messagingSenderId: '726617485507',
    projectId: 'signup-b4c76',
    storageBucket: 'signup-b4c76.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-Nv1gRaSCkxJv8tSNsuv9buYVetfzGc',
    appId: '1:726617485507:ios:1eef5c9dcbc1eb4341f276',
    messagingSenderId: '726617485507',
    projectId: 'signup-b4c76',
    storageBucket: 'signup-b4c76.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEepiSIP2F0ADO6qceMzx3WLqocEJl6o4',
    appId: '1:726617485507:web:4602a536ddc8708341f276',
    messagingSenderId: '726617485507',
    projectId: 'signup-b4c76',
    authDomain: 'signup-b4c76.firebaseapp.com',
    storageBucket: 'signup-b4c76.firebasestorage.app',
    measurementId: 'G-DDNFEG16HB',
  );

}